---
- name: Update Altair
  hosts: server
  vars_files:
    - vault.yml
  gather_facts: no
  vars:
    DIRECTORY: "yacs_altair"
  vars_prompt:
    - name: "version"
      prompt: "Enter version (leave empty for 'latest'):"
      private: no
      default: "latest"

  tasks:
    - name: Create folder
      ansible.builtin.command:
        cmd: "mkdir -p {{ DIRECTORY }}/{{ version }}"
      args:
        creates: "{{ DIRECTORY }}/{{ version }}"

    - name: Download files directly on the target device
      ansible.builtin.get_url:
        url: "ftp://{{ vault.FTP_USER_PROD }}:{{ vault.FTP_PASS_PROD }}@{{ vault.FTP_HOST_PROD }}/{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        dest: "{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - file: .env
        - file: setup.sh
          mode: "0755"
        - file: docker-compose-prod.yml
      loop_control:
        loop_var: item
      become: yes

    - name: Docker login for prod
      command: docker login {{ vault.HARBOR_HOST_PROD }} -u {{ vault.HARBOR_USER_PROD }} -p {{ vault.HARBOR_PASS_PROD }}
      become: no

    - name: Stop and remove Docker container
      ansible.builtin.docker_container:
        name: "{{ DIRECTORY }}"
        state: absent
        force_kill: yes

    - name: Execute setup.sh
      ansible.builtin.command:
        cmd: "./setup.sh {{ version }}"
        chdir: "{{ DIRECTORY }}/{{ version }}"
