---
- name: Update Bodypix Service
  hosts: server
  vars_files:
  - vault.yml
  gather_facts: no
  vars:
    DIRECTORY: "yacs_bodypix"
  vars_prompt:
    - name: Add  harbor hostname to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '2.12.100.145 harbor'
        state: present
    - name: Create folder
      ansible.builtin.command:
        cmd: "mkdir -p {{ DIRECTORY }}/{{ version }}"
      args:
        creates: "{{ DIRECTORY }}/{{ version }}"

    - name: Download files directly on the target device
      ansible.builtin.get_url:
        url: "ftp://{{ vault.FTP_USER_DEV }}:{{ vault.FTP_PASS_DEV }}@{{ vault.FTP_HOST_DEV }}/{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        dest: "{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - file: .env
        - file: setup.sh
          mode: "0755"
        - file: docker-compose-prod.yml
      loop_control:
        loop_var: item

    - name: Docker login for dev
      command: docker login {{ vault.HARBOR_HOST_DEV }} -u {{ vault.HARBOR_USER_DEV }} -p {{ vault.HARBOR_PASS_DEV }}
      
    - name: Stop and remove Docker container
      ansible.builtin.docker_container:
        name: "{{ DIRECTORY }}"
        state: absent
        force_kill: yes

    - name: Execute setup.sh
      ansible.builtin.command:
        cmd: "./setup.sh {{ version }}"
        chdir: "{{ DIRECTORY }}/{{ version }}"
