---
- name: Copy and Execute yacs-ntp.sh on remote servers
  hosts: portenta
  vars_files:
    - vault.yml
  gather_facts: no
  become: yes
  vars:
    DIRECTORY: "yacs_portenta_config/dev"

  tasks:
    - name: Copy yacs-ntp.sh to server
      ansible.builtin.get_url:
        url: "ftp://{{ vault.FTP_USER_DEV }}:{{ vault.FTP_PASS_DEV }}@{{ vault.FTP_HOST_DEV }}/{{ DIRECTORY }}/yacs-ntp.sh"
        dest: /tmp/yacs-ntp.sh
        mode: '0755'

    - name: Execute edit.sh on server
      command: /tmp/yacs-ntp.sh

