---
- name: Orangepi dependencies and Python installation
  hosts: orangepi
  vars_files:
    - vault.yml
  gather_facts: no
  become: yes

  tasks:
  - name: Update and install xdg-user-dirs
    apt:
      update_cache: yes
      name: xdg-user-dirs
      state: present
  
  - name: Add deadsnakes PPA for Python 3.10
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present

  - name: Install Python 3.10.10
    apt:
      name: python3.10
      state: present
    become: yes

  - name: Install Pip 22.3.1
    apt:
      name: python3-pip
      state: present
    become: yes
