---
- name: Copy and Execute edit.sh on remote servers
  hosts: orangepi
  vars_files:
    - vault.yml
  gather_facts: no
  become: yes

  tasks:
    - name: Copy edit.sh to server
      copy:
        src: /home/hazal/ansible-firefly/ansible-ntp/edit.sh  
        dest: /tmp/edit.sh
        mode: '0755'

    - name: Execute edit.sh on server
      command: /tmp/edit.sh

