- name: Update Echo Service
  hosts: orangepi
  vars_files:
    - vault.yml
  gather_facts: no
  become: yes
  vars:
    DIRECTORY: "yacs_echo"
    SERVICE_NAME: "yacs_echo"

  vars_prompt:
    - name: "version"
      prompt: "Enter version (leave empty for 'latest'):"
      private: no
      default: "latest"

  tasks:
    - name: Create folder
      ansible.builtin.command:
        cmd: "mkdir -p {{ DIRECTORY }}/{{ version }}"
      args:
        creates: "{{ DIRECTORY }}/{{ version }}"

    - name: Download files directly on the target device
      ansible.builtin.get_url:
        url: "ftp://{{ vault.FTP_USER_DEV }}:{{ vault.FTP_PASS_DEV }}@{{ vault.FTP_HOST_DEV }}/{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        dest: "{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - file: echo.zip
      loop_control:
        loop_var: item

    - name: Extract zip file
      ansible.builtin.unarchive:
        src: "{{ DIRECTORY }}/{{ version }}/echo.zip"
        dest: "{{ DIRECTORY }}/{{ version }}"
        remote_src: yes

    - name: Remove zip file
      ansible.builtin.file:
        path: "{{ DIRECTORY }}/{{ version }}/echo.zip"
        state: absent

    - name: Check if Poetry is installed
      command: poetry --version
      register: poetry_check
      failed_when: false
      changed_when: false

    - name: Install Poetry globally
      ansible.builtin.pip:
        name: poetry
        state: present
        executable: pip3
      when: poetry_check.rc != 0

    - name: Remove previous Poetry environments
      ansible.builtin.shell:
        cmd: "poetry env list --full-path | xargs -I {} rm -rf {}"
        chdir: "{{ DIRECTORY }}/{{ version }}"
      ignore_errors: yes

    - name: Install dependencies using Poetry
      ansible.builtin.command:
        cmd: "poetry install"
        chdir: "{{ DIRECTORY }}/{{ version }}"

    - name: Create service file
      become: yes
      copy:
        dest: "/etc/systemd/system/{{ SERVICE_NAME }}.service"
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description={{ SERVICE_NAME }}

          [Service]
          ExecStart=/usr/local/bin/poetry run python src/yacs_echo/main.py
          WorkingDirectory= /root/{{ DIRECTORY }}/{{ version }}
          User=root
          Group=root
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to make it aware of our service
      become: yes
      systemd:
        daemon_reload: yes

    - name: Ensure the service is running
      become: yes
      systemd:
        name: "{{ SERVICE_NAME }}"
        state: started
        enabled: yes