---
- name: Update slam maps
  hosts: firefly
  remote_user: svrn
  vars_files:
    - vault.yml
  gather_facts: no
  vars:
    DIRECTORY: "yacs_slam_maps"
  vars_prompt:
    - name: "version"
      prompt: "Enter version (leave empty for 'latest'):"
      private: no
      default: "latest"

  tasks:
    - name: Create folder
      ansible.builtin.command:
        cmd: "mkdir -p {{ DIRECTORY }}/{{ version }}"
      args:
        creates: "{{ DIRECTORY }}/{{ version }}"

    - name: Download files directly on the target device
      ansible.builtin.get_url:
        url: "ftp://{{ vault.FTP_USER_PROD }}:{{ vault.FTP_PASS_PROD }}@{{ vault.FTP_HOST_PROD }}/{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        dest: "{{ DIRECTORY }}/{{ version }}/{{ item.file }}"
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - file: setup_prod.sh
          mode: "0755"
        - file: current_map.yaml
      loop_control:
        loop_var: item

    - name: Read the contents of current_map.yaml
      slurp:
        src: "{{ DIRECTORY }}/{{ version }}/current_map.yaml"
      register: current_map_content

    - debug:
        msg: "{{ current_map_content['content']|b64decode|from_yaml }}"

    - name: Parse current_map.yaml contents
      set_fact:
        parsed_yaml: "{{ current_map_content['content'] | b64decode | from_yaml }}"

    - debug:
        msg: "{{ parsed_yaml }}"

    - name: Set parsed variables as facts
      set_fact:
        prod_folder_name: "{{ parsed_yaml['prod']['folder_name'] }}"
        prod_map_name: "{{ parsed_yaml['prod']['map_name'] }}"
        prod_md5sum: "{{ parsed_yaml['prod']['md5sum'] }}"

    - name: Pull {{ prod_folder_name }}.tar.gz from FTP
      get_url:
        url: "ftp://{{ vault.FTP_USER_PROD }}:{{ vault.FTP_PASS_PROD }}@{{ vault.FTP_HOST_PROD }}/{{ DIRECTORY }}/{{ version }}/{{ prod_folder_name }}.tar.gz"
        dest: "{{ DIRECTORY }}/{{ version }}/{{ prod_folder_name }}.tar.gz"

    - name: Execute script with .bashrc sourced
      ansible.builtin.shell:
        cmd: "bash -ic 'source ~/.bashrc && echo ROS2_WS: ${ROS2_WS} && ./setup_prod.sh'"
        chdir: "{{ DIRECTORY }}/{{ version }}"
      args:
        executable: /bin/bash
      become: true
      become_user: svrn

    - name: Read SAVED_MAPS_DIR from user's environment
      ansible.builtin.shell:
        cmd: "grep 'export SAVED_MAPS_DIR' ~/.bashrc | cut -d= -f2 | cut -d' ' -f2- | tr -d '\n'"
      register: saved_maps_dir_result
      become: true
      become_user: svrn

    - name: Print saved_maps_dir_result
      debug:
        msg: "{{ saved_maps_dir_result }}"

    - name: Set saved_maps_dir from the remote machine
      set_fact:
        saved_maps_dir: "{{ saved_maps_dir_result.stdout | default(omit) }}"
      when: saved_maps_dir_result.rc == 0

    - name: Check if SAVED_MAPS_DIR is defined
      fail:
        msg: "SAVED_MAPS_DIR is not defined in the environment"
      when: saved_maps_dir is undefined

    - name: Compare md5sum of currentMap file
      ansible.builtin.shell:
        cmd: "cd {{ saved_maps_dir }}/currentMap && md5sum {{ prod_map_name }}"
      register: md5sum_result

    - name: Print 'md5sum_result'
      debug:
        msg: "{{ md5sum_result }}"

    - name: Print 'prod_md5sum'
      debug:
        msg: "{{ prod_md5sum }}"

    - name: Check if md5sum matches prod_md5sum
      fail:
        msg: "md5sum check failed. Expected: {{ prod_md5sum }}, Actual: {{ md5sum_result.stdout.split()[0] }}"
      when: md5sum_result.stdout.split()[0] != prod_md5sum
